import type { FieldRef } from './views.service';

/**
 * One-click statistics computed over the result of a view's own query, via SQL window
 * functions — a different category from calculated fields (formula.ts), which compute a
 * per-row scalar. A quick stat is never placed on a shelf itself: it's added by right-clicking
 * an already-placed numeric field (its `sourceField`) and always shows up as an extra output
 * column appended after the view's normal fields.
 */
export type QuickStatKind = 'percent_of_total' | 'variation' | 'running_total' | 'rank' | 'moving_average';

export const QUICK_STAT_TABLE = '_stat';

export const QUICK_STAT_LABELS: Record<QuickStatKind, string> = {
  percent_of_total: '% du total',
  variation: 'Variation vs période précédente (%)',
  running_total: 'Cumul (total cumulé)',
  rank: 'Rang',
  moving_average: 'Moyenne mobile',
};

export interface QuickStatField {
  id: string;
  label: string;
  kind: QuickStatKind;
  /** The already-placed field (usually a measure) this stat is computed from. */
  sourceField: FieldRef;
  /** Ordering axis (typically a date/time dimension already on rows or columns) — required for variation, running_total and moving_average; unused otherwise. */
  orderField?: FieldRef;
  /** Number of periods (inclusive of the current one) averaged for moving_average. */
  windowSize?: number;
  /** Rank order — defaults to 'desc' (highest value = rank 1). */
  direction?: 'asc' | 'desc';
}

const KINDS_NEEDING_ORDER_FIELD: QuickStatKind[] = ['variation', 'running_total', 'moving_average'];

export function quickStatNeedsOrderField(kind: QuickStatKind): boolean {
  return KINDS_NEEDING_ORDER_FIELD.includes(kind);
}

/**
 * Builds the window-function SQL expression for a quick stat. `sourceAlias`/`orderAlias` are
 * synthetic column aliases (`col_0`, `col_1`, ...) generated by view-query-builder — never
 * user-controlled text — so they're safe to bind as `??` identifiers. `direction` is likewise
 * never user text: it can only be the literal 'asc' produced by the field's own typed union,
 * everything else falls back to 'desc'.
 */
export function compileQuickStatSql(field: QuickStatField, sourceAlias: string, orderAlias: string | null): { sql: string; bindings: (string | number)[] } {
  switch (field.kind) {
    case 'percent_of_total':
      // NULLIF guards the all-zero case rather than letting it surface as a division-by-zero error.
      return {
        sql: '(?? / NULLIF(SUM(??) OVER (), 0) * 100)',
        bindings: [sourceAlias, sourceAlias],
      };
    case 'variation': {
      if (!orderAlias) throw new Error('Le calcul "variation" nécessite un champ de tri (axe temporel).');
      return {
        sql: '((?? - LAG(??) OVER (ORDER BY ??)) / NULLIF(LAG(??) OVER (ORDER BY ??), 0) * 100)',
        bindings: [sourceAlias, sourceAlias, orderAlias, sourceAlias, orderAlias],
      };
    }
    case 'running_total': {
      if (!orderAlias) throw new Error('Le calcul "cumul" nécessite un champ de tri (axe temporel).');
      return {
        sql: 'SUM(??) OVER (ORDER BY ?? ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)',
        bindings: [sourceAlias, orderAlias],
      };
    }
    case 'rank': {
      const direction = field.direction === 'asc' ? 'ASC' : 'DESC';
      return {
        sql: `RANK() OVER (ORDER BY ?? ${direction})`,
        bindings: [sourceAlias],
      };
    }
    case 'moving_average': {
      if (!orderAlias) throw new Error('Le calcul "moyenne mobile" nécessite un champ de tri (axe temporel).');
      const periods = Math.max(1, Math.floor(field.windowSize ?? 3));
      return {
        sql: 'AVG(??) OVER (ORDER BY ?? ROWS BETWEEN ? PRECEDING AND CURRENT ROW)',
        bindings: [sourceAlias, orderAlias, periods - 1],
      };
    }
  }
}
